### ISSUE TITLE
RomFS block collision check code: edge case not being properly handled.

### ISSUE THREAD

**Issue by Zet-sensei** [DarkMatterCore/nxdumptool#39]
I'm trying to dump some games & updates from a 8.1.0 EUR Switch console - for backup and future preservation researches.

Everything went fine on all the games apart for 3 of them.

- Spice & Wolf VR (0100C9B00EAEE000)
- Geki J Pachisuro Hana Hana Matsuri! TOP5 Seizoroi SP / 激Jパチスロ ハナハナ祭り！TOP5勢ぞろいSP (0100FB500D8F8000)
- Soulslayer (010088E00EBB6000)

They can't be backup'ed with NXDumpTool 1.1.5. and the program throws an error when I try to create an NSP file.
![1](https://user-images.githubusercontent.com/52127625/65981123-bf684180-e478-11e9-91aa-cbad907af5e9.jpg)

RomFS an ExeFS can be dumped for the three of them.
![3](https://user-images.githubusercontent.com/52127625/65981212-eb83c280-e478-11e9-8374-5cca17edee0d.jpg)

Tried to dump these problematic games and updates with SX Installer 1.52.
I could extract the three mentioned games + updates and verified them.

![Wolf](https://user-images.githubusercontent.com/52127625/65982082-c2fcc800-e47a-11e9-98ec-eff1db1a498b.jpg)

Seems to be a bug inside NXDumpTool that I want to report and to be checked.

**Comment by DarkMatterCore** [comment]
Thanks for reporting this problem. I'll gladly look into it.

The RomFS browse/dump feature isn't exactly related to this particular error, because it deals with the Program NCA. On the other hand, the RomFS error you're getting it's actually related to the NACP/LegalInfo XML extraction procedure - both files get appended to the output NSP dump.

Please test the provided build in the meantime. It will create a "debug.txt" file in the SD card root directory whenever this particular error is triggered - paste its contents to this conversation.

[nxdumptool_test_20191001.zip](https://github.com/DarkMatterCore/nxdumptool/files/3677686/nxdumptool_test_20191001.zip)

**Comment by Zet-sensei** [comment]
```
ncaId: f56098adbc80648435ad38df75bf5c7d

section_offset: 0x0000000000000C00
section_size: 0x0000000000030400
section_offset + section_size: 0x0000000000031000

romfs_offset: 0x0000000000014C00
romfs_size: 0x000000000001C400

romfs_offset + romfs_size: 0x0000000000031000
romfs_dirtable_offset: 0x0000000000030F7C
romfs_dirtable_size: 0x0000000000000018
romfs_dirtable_offset + romfs_dirtable_size: 0x0000000000030F94
romfs_filetable_offset: 0x0000000000030FA0
romfs_filetable_size: 0x0000000000000060
romfs_filetable_offset + romfs_filetable_size: 0x0000000000031000
```

**Comment by DarkMatterCore** [comment]
Thanks. It was indeed a bug in the RomFS block collision check code. The RomFS section from the Control/LegalInfo NCAs in these games fall under edge cases that were not being properly handled. Please test the attached build.

[nxdumptool_test2_20191001.zip](https://github.com/DarkMatterCore/nxdumptool/files/3678085/nxdumptool_test2_20191001.zip)

**Comment by Zet-sensei** [comment]
Works perfectly now.

Great job for fixing the problem very quickly.

Thanks.

**Comment by Zet-sensei** [comment]
Works perfectly now.

Great job for fixing the problem very quickly.

Thanks.

**Comment by DarkMatterCore** [comment]
Thank **you** for reporting the issue! You're the real lifesaver.

I'll reopen the issue and keep it like that until I release the next version.

**Comment by DarkMatterCore** [comment]
Fixed in 4d44e315be948fafd924f861926dc4fa5657035f.

**Comment by SK91no** [comment]
![2022061500593400-A18332D608210216D3CD45106FD5B466](https://user-images.githubusercontent.com/63129189/173703590-407a6d77-b481-4bf5-81cd-8fccac03f507.jpg)
I still get this error when trying to dump RomFS for Gal*Gun Double Peace (ExeFS and NSP creation work fine)
